#!/usr/bin/env bash

DB_NAME=$(cat company-name)
LIBS="ERL_LIBS=`lfetool info erllibs`"
SCRIPT_WRAP="-s roz-script format-run"
DB="-mnesia dir \'\"$DB_NAME\"\'"
LFE="$LIBS ./deps/lfe/bin/lfe -noshell $DB $SCRIPT_WRAP"
LFEC="$LIBS ./deps/lfe/bin/lfec"
FINISH="-s erlang halt"

print-usage () {
    lfe
}

error () {
    message=$1
    echo
    echo $message
    echo
    print-usage $script
    exit 1
}

unknown-command-error () {
    command=$1
    error "Unknown command: '$command'";
}

do-help () {
    echo
}

do-version () {
    echo
}

do-repl () {
    echo "Starting roz REPL ..."
    echo
    make mnesia-shell
}

do-init () {
    echo "Initializing roz data ..."
    echo
    eval $LFE roz init $FINISH
}

do-add-group () {
    echo "Adding group '$1' ..."
    echo
    command="$LFE roz-content add-group $@ $FINISH"
    #echo "comand: $command"
    eval $command
}

run-add () {
    subcommand=$1
    groupname=$2
    case $subcommand in
        group)
            echo
            do-add-group "$groupname"
            exit 0
            ;;
    esac
}

run () {
    script=$0
    command=$1
    subcommand=$2
    shift 2
    case $command in
        -h|help)
            do-help
            exit o
            ;;
        -v|version)
            do-version
            exit 0
            ;;
        init)
            do-init
            exit 0
            ;;
        add)
            do-add-group $cubcommand "$@"
            exit 0
            ;;
        repl)
            do-repl
            ;;
        *)
            unknown-command-error $command
            ;;
    esac
}

run "$@"
